 - name: download artifact from nexus server
   become: yes
   get_url:
     url: http://18.180.78.195:8081/repository/demoproject-snapshot/com/example/springboot/1.2.1-SNAPSHOT/springboot-1.2.1-20221226.174350-28.war
     dest: /opt/tomcat/apache-tomcat-10.0.8/webapps
